mysql:
  user-resource: root:meixi253@tcp(47.109.159.227:3306)/userService?charset=utf8mb4&parseTime=true&loc=Local
  file-resource: root:meixi253@tcp(47.109.159.227:3306)/fileService?charset=utf8mb4&parseTime=true&loc=Local
  user-file-resource: root:meixi253@tcp(47.109.159.227:3306)/userFileService?charset=utf8mb4&parseTime=true&loc=Local
redis:
  addr: 47.109.159.227:6379
  db: 1
  username:
  password: meixi253
  read_timeout: 0.2
  write_timeout: 0.2
  dial_timeout: 0.2
local-store: ./static/tmp
local-mp-store: ./static/mp
user-service-name : user-server
file-service-name : file-server
user-file-service-name : user-file-server
dtmServer : 127.0.0.1:36790
mqAddr : amqp://gua:meixi253@47.109.159.227:5672/
mqUploadExchangeName : filestore-oss
mqUploadQueue : filestore-channel-oss
mqUploadKey : oss
ossEndpoint : oss-cn-chengdu.aliyuncs.com
ossAccessKeyId : LTAI5tPDgNhMFBo2BSvEdEcr
ossAccessKeySecret : 8ixhBPsARwQtljRN4LcdaZu9IXlMbg
