mysql:
  user-resource: root:meixi253@tcp(47.109.159.227:3306)/userService?charset=utf8mb4&parseTime=true&loc=Local
  file-resource: root:meixi253@tcp(47.109.159.227:3306)/fileService?charset=utf8mb4&parseTime=true&loc=Local
  user-file-resource: root:meixi253@tcp(47.109.159.227:3306)/userFileService?charset=utf8mb4&parseTime=true&loc=Local
redis:
  addr: 47.109.159.227:6379
  db: 1
  username:
  password: meixi253
  read_timeout: 0.2
  write_timeout: 0.2
  dial_timeout: 0.2
local-store: ./static/tmp
user-service-name : user-server
file-service-name : file-server
user-file-service-name : user-server
dtmServer : 127.0.0.1:36790